### ISSUE TITLE
Error running dev copy

### ISSUE THREAD

**Issue by andrewelkins** [wlaurance/slack-for-linux#37]
I've pulled down the latest code from github.

```
git clone https://github.com/wlaurance/slack-for-linux.git
cd slack-for-linux/
npm install
./run.js
```
Which results in:
```
# ./run.js 

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:1011:11)
    at Process.ChildProcess._handle.onexit (child_process.js:802:34)

```

Any tips on resolving it?

**Comment by twolfson** [comment]
It sounds like its failing to find the build `slack4linux`:

https://github.com/wlaurance/slack-for-linux/blob/v1.2.1/run.js#L4

Were there any errors during the `npm install`?

**Comment by andrewelkins** [comment]
No errors on install. Now that 30 is in. Let re checkout and attempt to install again.

**Comment by andrewelkins** [comment]
Got an error this time:

```
# npm install
npm WARN cannot run in wd slack-for-linux@1.3.0 ./install.sh (wd=/opt/slack-for-linux)
grunt-cli@0.1.13 node_modules/grunt-cli
├── resolve@0.3.1
├── nopt@1.0.10 (abbrev@1.0.5)
└── findup-sync@0.1.3 (glob@3.2.11, lodash@2.4.2)

grunt-contrib-jshint@0.10.0 node_modules/grunt-contrib-jshint
├── hooker@0.2.3
└── jshint@2.5.11 (strip-json-comments@1.0.2, underscore@1.6.0, exit@0.1.2, console-browserify@1.1.0, minimatch@1.0.0, shelljs@0.3.0, cli@0.6.6, htmlparser2@3.8.2)

grunt-lintspaces@0.6.2 node_modules/grunt-lintspaces
└── lintspaces@0.2.3 (editorconfig@0.11.4, merge@1.1.2)

grunt-jscs@1.8.0 node_modules/grunt-jscs
├── vow@0.4.9
├── hooker@0.2.3
├── lodash@2.4.2
└── jscs@1.13.0 (strip-json-comments@1.0.2, pathval@0.1.1, commander@2.6.0, estraverse@1.9.3, chalk@1.0.0, exit@0.1.2, glob@5.0.5, cli-table@0.3.1, lodash.assign@3.0.0, minimatch@2.0.4, vow-fs@0.3.4, esprima-harmony-jscs@1.1.0-bin, esprima@1.2.5, prompt@0.2.14, xmlbuilder@2.6.2)

grunt-node-webkit-builder@1.0.2 node_modules/grunt-node-webkit-builder
└── node-webkit-builder@1.0.11 (platform-overrides@1.0.1, inherits@2.0.1, progress@1.1.8, rcedit@0.2.0, temp@0.7.0, semver@2.3.2, optimist@0.6.1, graceful-fs-extra@1.0.6, simple-glob@0.1.0, rimraf@2.3.2, graceful-ncp@2.0.0, decompress-zip@0.0.8, bluebird@1.2.4, tar-fs@0.3.3, request@2.40.0, winresourcer@0.9.0, archiver@0.13.1, lodash@2.4.2, update-notifier@0.1.10, plist@1.1.0)

grunt@0.4.5 node_modules/grunt
├── which@1.0.9
├── dateformat@1.0.2-1.2.3
├── eventemitter2@0.4.14
├── getobject@0.1.0
├── rimraf@2.2.8
├── colors@0.6.2
├── async@0.1.22
├── grunt-legacy-util@0.2.0
├── exit@0.1.2
├── nopt@1.0.10 (abbrev@1.0.5)
├── minimatch@0.2.14 (sigmund@1.0.0, lru-cache@2.6.2)
├── lodash@0.9.2
├── hooker@0.2.3
├── glob@3.1.21 (inherits@1.0.0, graceful-fs@1.2.3)
├── coffee-script@1.3.3
├── underscore.string@2.2.1
├── iconv-lite@0.2.11
├── js-yaml@2.0.5 (argparse@0.1.16, esprima@1.0.4)
├── findup-sync@0.1.3 (glob@3.2.11, lodash@2.4.2)
└── grunt-legacy-log@0.1.1 (underscore.string@2.3.3, lodash@2.4.2)

bower@1.4.1 node_modules/bower
├── is-root@1.0.0
├── junk@1.0.1
├── stringify-object@1.0.1
├── user-home@1.1.1
├── which@1.0.9
├── abbrev@1.0.5
├── chmodr@0.1.0
├── rimraf@2.3.2
├── archy@1.0.0
├── opn@1.0.2
├── bower-logger@0.2.2
├── bower-endpoint-parser@0.2.2
├── graceful-fs@3.0.6
├── lockfile@1.0.0
├── nopt@3.0.1
├── lru-cache@2.6.2
├── retry@0.6.1
├── tmp@0.0.24
├── request-progress@0.3.1 (throttleit@0.0.2)
├── q@1.3.0
├── shell-quote@1.4.3 (array-filter@0.0.1, array-reduce@0.0.0, array-map@0.0.0, jsonify@0.0.0)
├── p-throttler@0.1.1 (q@0.9.7)
├── mkdirp@0.5.0 (minimist@0.0.8)
├── bower-json@0.4.0 (intersect@0.0.3, deep-extend@0.2.11, graceful-fs@2.0.3)
├── promptly@0.2.0 (read@1.0.5)
├── chalk@1.0.0 (escape-string-regexp@1.0.3, ansi-styles@2.0.1, supports-color@1.3.1, strip-ansi@2.0.1, has-ansi@1.0.3)
├── fstream@1.0.4 (inherits@2.0.1)
├── semver@2.3.2
├── insight@0.5.3 (object-assign@2.0.0, lodash.debounce@3.0.3, async@0.9.0, os-name@1.0.3, tough-cookie@0.12.1)
├── fstream-ignore@1.0.2 (inherits@2.0.1, minimatch@2.0.4)
├── tar-fs@1.5.0 (pump@1.0.0, tar-stream@1.1.4)
├── glob@4.5.3 (inherits@2.0.1, inflight@1.0.4, once@1.3.1, minimatch@2.0.4)
├── decompress-zip@0.1.0 (mkpath@0.1.0, touch@0.0.3, readable-stream@1.1.13, binary@0.3.0)
├── update-notifier@0.3.2 (is-npm@1.0.0, string-length@1.0.0, semver-diff@2.0.0, latest-version@1.0.0)
├── github@0.2.4 (mime@1.3.4)
├── cardinal@0.4.4 (ansicolors@0.2.1, redeyed@0.4.4)
├── bower-registry-client@0.3.0 (graceful-fs@2.0.3, request-replay@0.2.0, rimraf@2.2.8, lru-cache@2.3.1, async@0.2.10, mkdirp@0.3.5, request@2.51.0)
├── request@2.53.0 (caseless@0.9.0, json-stringify-safe@5.0.0, aws-sign2@0.5.0, forever-agent@0.5.2, stringstream@0.0.4, oauth-sign@0.6.0, tunnel-agent@0.4.0, isstream@0.1.2, qs@2.3.3, combined-stream@0.0.7, node-uuid@1.4.3, mime-types@2.0.10, form-data@0.2.0, bl@0.9.4, http-signature@0.10.1, hawk@2.3.1, tough-cookie@1.1.0)
├── mout@0.11.0
├── bower-config@0.6.1 (osenv@0.0.3, graceful-fs@2.0.3, optimist@0.6.1, mout@0.9.1)
├── configstore@0.3.2 (object-assign@2.0.0, xdg-basedir@1.0.1, osenv@0.1.0, uuid@2.0.1, js-yaml@3.3.0)
├── inquirer@0.8.0 (figures@1.3.5, through@2.3.7, ansi-regex@1.1.1, readline2@0.1.1, mute-stream@0.0.4, chalk@0.5.1, lodash@2.4.2, cli-color@0.3.3, rx@2.5.2)
└── handlebars@2.0.0 (optimist@0.3.7, uglify-js@2.3.6)
```

**Comment by twolfson** [comment]
That's a warning not an error. It looks like everything installed fine. There is typically more though (e.g. an `./install.sh`) as part of the `postinstall`. Did that run too?

**Comment by wlaurance** [comment]
I believe because of the warning, NPM will not run the install.sh post install script.

http://stackoverflow.com/questions/18136746/npm-install-failed-with-cannot-run-in-wd

**Comment by wlaurance** [comment]
@andrewelkins Try `npm install --unsafe-perm`

What's your `npm --version`?

**Comment by andrewelkins** [comment]
```
$ npm --version
1.4.28
$ nodejs -v
v0.10.37
```

**Comment by andrewelkins** [comment]
Ubuntu 14.04 in case that's needed

**Comment by andrewelkins** [comment]
`npm install --unsafe-perm` worked! Now time to test. Thanks!

**Comment by wlaurance** [comment]
I noticed that it was trying to install into `/opt`? Is that correct

**Comment by twolfson** [comment]
Ooooh, I see what happened. You cloned the repo into `/opt/slack-for-linux`. For development work, I suggest cloning into a home directory and using `npm link` (which will create a symlink to the `bin`).
