### ISSUE TITLE
Opens a blank screen after updating

### ISSUE THREAD

**Issue by PlatinumSeed** [wlaurance/slack-for-linux#43]
I've just updated to version 1.4. After that all I get is a blank white page when I open it. Also tried removing completely and reinstalling.

I did get the following messages during installation:

>> Local Npm module "grunt-contrib-jshint" not found. Is it installed?
>> Local Npm module "grunt-jscs" not found. Is it installed?
>> Local Npm module "grunt-lintspaces" not found. Is it installed?

**Comment by dnh-ee** [comment]
I've got the same issue. Downgrading to 1.2.1 causes it to resume working, and upgrading again breaks it again.
I'm on Ubuntu 14.04, and I saw exactly the same warnings as PlatinumSeed during installation.

**Comment by twolfson** [comment]
Hmmm, it sounds like something was broken with respect to cookies. I have a feeling those `grunt` task complaints are red herrings. I will take by the end of this weekend.

**Comment by dnh-ee** [comment]
Is there a log location or something I look at to provide you with more information?

**Comment by twolfson** [comment]
Unfortunately, no but we will definitely be adding something =)

**Comment by twolfson** [comment]
I have successfully reproduced the error. Going to see if we can find the source from here.

**Comment by twolfson** [comment]
Ah, it looks like bundling which worked in local development and testing within a development folder has broken in a published environment:

```bash
$ /usr/local/lib/node_modules/slack-for-linux/./webkitbuilds/slack4linux/linux64/slack4linux
[17371:0430/010941:ERROR:browser_main_loop.cc(170)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
[17371:0430/010941:ERROR:nw_shell.cc(335)] Error: Cannot find module 'underscore'
    at Function.Module._resolveFilename (module.js:327:15)
    at Function.Module._load (module.js:264:25)
    at Module.require (module.js:356:17)
    at require (module.js:375:17)
    at window.require (<anonymous>:4:17)
    at file:///tmp/.org.chromium.Chromium.fTGPDT/js/index.js:6:10
    at file:///tmp/.org.chromium.Chromium.fTGPDT/js/index.js:291:3
[17371:0430/010941:INFO:CONSOLE(329)] "Uncaught Error: Cannot find module 'underscore'", source: module.js (329)
[17371:0430/010941:ERROR:nw_shell.cc(335)] TypeError: Cannot read property 'load' of undefined
    at file:///tmp/.org.chromium.Chromium.fTGPDT/views/index.html:11:20
[17371:0430/010941:INFO:CONSOLE(11)] "Uncaught TypeError: Cannot read property 'load' of undefined", source: file:///tmp/.org.chromium.Chromium.fTGPDT/views/index.html (11)
[17401:0430/010952:WARNING:channel.cc(553)] Failed to send message to ack remove remote endpoint (local ID 1, remote ID 1)
```

**Comment by twolfson** [comment]
This is very strange, the `node_modules/` aren't in the installed directory for the app:

```bash
$ ls /usr/local/lib/node_modules/slack-for-linux/app/
bower_components  bower.json  css  images  js  package.json  views
```

Going to look at a verbose install log to see what's happening.

**Comment by twolfson** [comment]
It seems like the `--global` and `--verbose` flag are being carried between nested `npm install's`. I am looking into how to force it to not do that =/

**Comment by twolfson** [comment]
Ah, I have found out how to override it. `npm` is passing through these settings via `env`. We should be able to override:

```
npm_config_global=true
```

**Comment by twolfson** [comment]
Okay, the override worked and the app seems to be running. I will be opening a PR shortly.

**Comment by twolfson** [comment]
Alright, https://github.com/wlaurance/slack-for-linux/pull/45 has been opened and should resolve this issue. Thanks for the bug report and sorry for the inconvenience!

**Comment by PlatinumSeed** [comment]
No problem, thanks for being on top of all these issues :)

**Comment by dnh-ee** [comment]
+1
